<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <!-- <OutputType>Exe</OutputType> -->
    <RootNamespace>PKVault.Backend</RootNamespace>
    <!-- <PublishAot>true</PublishAot> -->
    <!-- <IsAotCompatible>true</IsAotCompatible> -->
    
    <!-- <PublishSingleFile>true</PublishSingleFile> -->
    <!-- <SelfContained>true</SelfContained> -->

    <Product>PKVault</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.3.1" />
    <ProjectReference Include="..\PKVault.Core\PKVault.Core.csproj" />
  </ItemGroup>
</Project>
