// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PKVault.Core;

#nullable disable

namespace PKVault.Core.Migrations
{
    [DbContext(typeof(SessionDbContext))]
    [Migration("20261002002640_AddInventoryItemTable")]
    partial class AddInventoryItemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BankEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdInt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("MetaEntity", b =>
                {
                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("PKVault.Core.BoxEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdInt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InventoryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("PKVault.Core.DexFormEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Context")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Form")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaught")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaughtAlpha")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaughtShiny")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Species")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Form");

                    b.HasIndex("Gender");

                    b.HasIndex("Species");

                    b.ToTable("Pokedex");
                });

            modelBuilder.Entity("PKVault.Core.InventoryItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BoxId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdInt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Item")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoxId");

                    b.HasIndex("ItemKey");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("PKVault.Core.PkmFileEntity", b =>
                {
                    b.Property<string>("Filepath")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Error")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Filepath");

                    b.ToTable("PkmFiles");
                });

            modelBuilder.Entity("PKVault.Core.PkmVariantEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("AttachedSaveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachedSavePkmIdBase")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoxId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BoxSlot")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Context")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Form")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Generation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlpha")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsShiny")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Species")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttachedSaveId")
                        .HasFilter("AttachedSaveId IS NOT NULL");

                    b.HasIndex("BoxId");

                    b.HasIndex("Filepath")
                        .IsUnique();

                    b.HasIndex("AttachedSaveId", "AttachedSavePkmIdBase")
                        .HasFilter("AttachedSaveId IS NOT NULL");

                    b.HasIndex("BoxId", "BoxSlot");

                    b.HasIndex("Species", "Form", "Gender");

                    b.HasIndex("Species", "Form", "Gender", "IsShiny");

                    b.ToTable("PkmVersions");
                });

            modelBuilder.Entity("PKVault.Core.BoxEntity", b =>
                {
                    b.HasOne("BankEntity", null)
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PKVault.Core.PkmVariantEntity", b =>
                {
                    b.HasOne("PKVault.Core.BoxEntity", null)
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PKVault.Core.PkmFileEntity", "PkmFile")
                        .WithOne()
                        .HasForeignKey("PKVault.Core.PkmVariantEntity", "Filepath")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PkmFile");
                });
#pragma warning restore 612, 618
        }
    }
}
