
public static class DtoCompareProperties
{
    public static readonly HashSet<string> PkmVariantPropertiesToUse = [
        // "IsMain",
        // "IsExternal",
        // "AttachedSaveId",
        // "AttachedSavePkmIdBase",
        // "IsFilePresent",
        // "Filepath",
        // "FilepathAbsolute",
        // "VersionChecker",
        // "CanMoveAttachedToSave",
        // "CanDelete",
        // "CanMoveToSave",
        // "CanEdit",
        // "CanEvolve",
        // "CanCreateVariant",
        // "CompatibleWithVersions",
        // "Id",
        "Generation",
        // "BoxId",
        // "BoxSlot",
        // "IsDuplicate",
        // "SettingsLanguage",
        // "Pkm",
        // "Evolves",
        "IdBase",
        // "BoxKey",
        "Version",
        "ContextVersion",
        "Context",
        "PID",
        "IsNicknamed",
        "Nickname",
        "Species",
        "Form",
        "IsEgg",
        "IsShiny",
        "IsAlpha",
        "IsNoble",
        // "NSparkle",
        // "CanGigantamax",
        "Ball",
        "Gender",
        "Types",
        "TeraType",
        "Level",
        "Exp",
        "ExpToLevelUp",
        "LevelUpPercent",
        "Friendship",
        // "EggHatchCount",
        "IVs",
        "EVs",
        "Stats",
        "BaseStats",
        "HiddenPowerType",
        "HiddenPowerPower",
        "HiddenPowerCategory",
        "Nature",
        "Ability",
        "AbilityNumber",
        "IsAbilityHidden",
        "Moves",
        "RelearnMoves",
        "AlphaMove",
        // "TID",
        // "SID",
        "OriginTrainerName",
        "OriginTrainerGender",
        // "HandlingTrainerName",
        // "HandlingTrainerGender",
        // "HandlingTrainerFriendship",
        "IsCurrentHandler",
        "OriginMetDate",
        "OriginMetLocation",
        "OriginMetLevel",
        "FatefulEncounter",
        "HeldItem",
        // "DynamicChecksum",
        // "NicknameMaxLength",
        "LanguageID",
        "HomeTracker",
        "Markings",
        "Contest",
        "Ribbons",
        "PokerusStrain",
        "PokerusDays",
        "IsPokerusInfected",
        "IsPokerusCured",
        "IsShadow",
        // "CanMove",
        // "LoadError",
        // "HasLoadError",
        // "IsEnabled",
    ];

    public static readonly HashSet<string> PkmLegalityPropertiesToUse = [
        // "Id",
        // "SaveId",
        "MovesLegality",
        "RelearnMovesLegality",
        "IsValid",
        "ValidityReport",
        "IllegalitiesCount",
    ];
}
