import z from 'zod';

const baseURL = new URL(window.location.href).searchParams.get('server') || window.location.origin;

console.log('Server url =>', baseURL);

export const getApiFullUrl = (url: string) => `${baseURL}${url}`;

export type ResponseBack<D = unknown> = z.infer<typeof responseBackSchema> & { data: D }
export const responseBackSchema = z.object({
    // data: z.unknown(),
    headers: z.instanceof(Headers),
    status: z.number().int(),
});

export type SerializableResponse = Pick<Response, 'url' | 'ok' | 'status' | 'statusText' | 'headers'> & {
    body?: string;
};

export const customInstance = async <T extends ResponseBack>(url: string, init?: RequestInit): Promise<T> => {
    const targetUrl = normalizeUrlParams(getApiFullUrl(url));

    try {
        if (window.HybridWebView) {

            const res = await window.HybridWebView.InvokeDotNet("Fetch", [ targetUrl, init ]);

            const headers = new Headers(res.headers);

            if (!res.ok) {
                throw new QueryError({ ...res, headers });
            }

            const body = res.body?.toString();
            const data = body ? JSON.parse(body) : {};

            return { data, status: res.status, headers } satisfies ResponseBack as T;
        }

        const res = await fetch(targetUrl, init);

        if (!res.ok) {
            throw new QueryError(res);
        }

        const body = [ 204, 205, 304 ].includes(res.status) ? null : await res.text();
        const data = body ? JSON.parse(body) : {};

        return { data, status: res.status, headers: res.headers } satisfies ResponseBack as T;
    } catch(err) {
        throw new QueryError({
            url: targetUrl,
            status: 500,
            statusText: 'Internal Error',
            headers: new Headers(),
        }, err instanceof Error ? err : undefined);
    }
};

/**
 * Normalize url params removing 'null' values generated by Orval.
 */
const normalizeUrlParams = (url: string): string => {
    const urlObj = new URL(url);

    const searchParams = new URLSearchParams();

    urlObj.searchParams.forEach((value, key) => {
        if (value !== 'null') {
            searchParams.append(key, value);
        }
    });

    urlObj.search = '?' + searchParams;

    return urlObj.href;
};

export default customInstance;

export class QueryError extends Error {
    public readonly url: string;
    public readonly status: number;
    public readonly statusText: string;
    public readonly errorMessage: string | null;
    public readonly errorStack: string | null;

    constructor(res: Pick<SerializableResponse, 'url' | 'status' | 'statusText' | 'headers'>, error?: Error) {
        const errorMessage = error?.message ?? QueryError.getHeaderContent(res.headers.get('error-message'));
        const errorStack = error?.stack ?? QueryError.getHeaderContent(res.headers.get('error-stack'));

        super("Query error:"
            + `\nurl = ${res.url}`
            + `\nstatus = ${res.status} / ${res.statusText}`
            + `\nerror message = ${errorMessage}`
            + `\nerror stack =\n${errorStack}`);

        this.url = res.url;
        this.status = res.status;
        this.statusText = res.statusText;
        this.errorMessage = errorMessage;
        this.errorStack = errorStack;

        Object.setPrototypeOf(this, QueryError.prototype);

        console.error(this.message);
    }

    private static getHeaderContent(value: string | null): string | null {
        try {
            return JSON.parse(value!);
        } catch (_) {
            return value;
        }
    }
}

// override the return error type
export type ErrorType<_> = QueryError;

// // In case you want to wrap the body type (optional)
// // (if the custom instance is processing data before sending it, like changing the case for example)
// export type BodyType<BodyData> = CamelCase<BodyType>;
