<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <!-- <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages> -->
    
    <PublishTrimmed>true</PublishTrimmed>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

    <!-- can be used for lib trimmed debug -->
    <!-- <EnableTrimAnalyzer>true</EnableTrimAnalyzer> -->

    <!-- hides verbose trim warnings that cannot be solved, for AspNetCore.Mvc, EF Core, and other libs -->
    <NoWarn>IL2026;IL2037;IL2104</NoWarn>

    <RuntimeIdentifiers>
      win-x64;
      linux-x64;
      linux-arm64;
      osx-x64;
      osx-arm64
    </RuntimeIdentifiers>

    <AssemblyName>PKVault</AssemblyName>
    <ApplicationTitle>PKVault</ApplicationTitle>
    <ApplicationId>com.chnapy.pkvault</ApplicationId>
    <Version>2.2.1</Version>
    <ApplicationDisplayVersion>2.2.1</ApplicationDisplayVersion>
    <ApplicationVersion>2.2.1</ApplicationVersion>
    <ApplicationIcon>Resources/wwwroot/icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NeutralLanguage>en</NeutralLanguage>
    <Product>PKVault</Product>
    <Description>PKVault is a Pokemon storage and save manipulation tool based on PKHeX.</Description>
    <AssemblyDescription>PKVault is a Pokemon storage and save manipulation tool based on PKHeX.</AssemblyDescription>
    <Authors>Richard Haddad</Authors>
    <Copyright>Richard Haddad</Copyright>
    <SourceRevisionId>$([System.DateTime]::UtcNow.ToString("yyMMddHHmmss"))</SourceRevisionId>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Chnapy/PKVault</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Chnapy/PKVault</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/wwwroot/**/*" />

    <TrimmerRootDescriptor Include="linker.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="12.1.1" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <!-- <Target Name="RemoveAngleNativeLib" AfterTargets="ComputeFilesToPublish">
    <ItemGroup>
      <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(FileName)%(Extension)' == 'av_libglesv2.dll'" />
    </ItemGroup>
  </Target> -->

  <ItemGroup>
    <ProjectReference Include="..\PKVault.Backend\PKVault.Backend.csproj" />
  </ItemGroup>
</Project>
